/**
 * Seed synthetic fraud cases for the Fraud Intelligence Center.
 *
 * WARNING: All data generated by this script is fictional.
 * No real account numbers, names, or PII are used.
 */

const { fraudDb, db } = require('../services/database');
const { generateCase, persistCase } = require('../lib/fraudGenerator');

function seed(count = 1000) {
    console.log(`Seeding ${count} synthetic fraud cases...`);
    db.prepare('DELETE FROM fraud_cases').run();

    const insert = db.transaction(() => {
        for (let i = 0; i < count; i++) {
            const c = generateCase(i, count);
            persistCase(c, fraudDb, {
                note: Math.random() < 0.3 ? `Initial triage: ${c.riskFactors.slice(0, 3).join(', ')} flagged.` : null
            });
        }
    });

    insert();
    console.log(`Seeded ${count} fraud cases.`);
}

const count = parseInt(process.argv[2], 10) || 1000;
seed(count);
