import { useEffect, useState } from 'react';
import { useWealthStore } from '@/shared/store/wealthStore';
import { generateMonthlyNarrative, type MonthlyNarrative } from '@/shared/services/llmService';

export default function MonthlyNarrative() {
  const transactions = useWealthStore((s) => s.transactions);
  const goals = useWealthStore((s) => s.goals);
  const user = useWealthStore((s) => s.user);
  const [narrative, setNarrative] = useState<MonthlyNarrative | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const debits = transactions.filter((t) => t.type === 'debit' && t.status === 'ALLOWED');
    const totalExpenses = debits.reduce((s, t) => s + t.amount, 0);
    const totalSavings = user.monthlySavings;
    const savingsRate = user.monthlyIncome > 0 ? (totalSavings / user.monthlyIncome) * 100 : 0;

    const byCategory: Record<string, number> = {};
    debits.forEach((t) => {
      byCategory[t.category] = (byCategory[t.category] || 0) + t.amount;
    });
    const topCat = Object.entries(byCategory).sort((a, b) => b[1] - a[1])[0];

    const goalProgress = goals.length > 0
      ? goals.reduce((s, g) => s + (g.currentAmount / g.targetAmount), 0) / goals.length * 100
      : 0;

    const fraudBlocked = transactions.filter((t) => t.status === 'BLOCKED').length;

    generateMonthlyNarrative({
      savingsRate,
      topExpenseCategory: topCat?.[0] || 'General',
      topExpenseAmount: topCat?.[1] || 0,
      goalProgress,
      totalSavings,
      totalExpenses,
      fraudBlocked,
    }).then((n) => {
      setNarrative(n);
      setLoading(false);
    });
  }, [transactions, goals, user]);

  if (loading) {
    return (
      <div className="card animate-pulse">
        <div className="h-4 bg-slate-200 dark:bg-slate-700 rounded w-1/3 mb-3" />
        <div className="h-3 bg-slate-200 dark:bg-slate-700 rounded w-full mb-2" />
        <div className="h-3 bg-slate-200 dark:bg-slate-700 rounded w-5/6" />
      </div>
    );
  }

  if (!narrative) return null;

  return (
    <div className="card bg-gradient-to-br from-violet-50 to-indigo-50 dark:from-violet-900/10 dark:to-indigo-900/10 border-2 border-violet-200 dark:border-violet-800">
      <div className="flex items-center gap-3 mb-3">
        <div className="w-10 h-10 rounded-xl bg-violet-100 flex items-center justify-center text-violet-600 text-lg">
          <span>{narrative.emojiMood}</span>
        </div>
        <div>
          <p className="text-[10px] text-violet-500 uppercase tracking-wider font-bold">Your Month in Money</p>
          <h3 className="font-bold text-sm text-slate-800 dark:text-white">{narrative.headline}</h3>
        </div>
      </div>

      <div className="p-3 bg-white/60 dark:bg-slate-900/40 rounded-xl border border-violet-100 dark:border-violet-800/30 mb-3">
        <p className="text-xs font-semibold text-violet-700 dark:text-violet-300 mb-2">{narrative.highlight}</p>
        {narrative.paragraphs.map((p, idx) => (
          <p key={idx} className="text-xs text-slate-600 dark:text-slate-300 leading-relaxed mb-1.5 last:mb-0">
            {p}
          </p>
        ))}
      </div>

      <div className="flex items-center gap-2 text-[10px] text-slate-400">
        <i className="fas fa-wand-magic-sparkles text-violet-400" />
        <span>Generated by SecureWealth AI · On-Device Intelligence</span>
      </div>
    </div>
  );
}
